### ISSUE TITLE
Getting filters causes AttributeError

### ISSUE THREAD

**Issue by paul-wolf** [concentricsky/django-tastypie-swagger#101]
Django: 1.7.4
Tastypie: 0.12.1
django-tastypie-swagger: 0.1.4

In mapping.py, Line 191: `self.schema['filtering']` is expected to be a dict, but it's a tuple. 

``` 
    for name, field in self.schema['filtering'].items():
    AttributeError: 'tuple' object has no attribute 'items'
```

Source:

```
        if 'filtering' in self.schema and method.upper() == 'GET':
            for name, field in self.schema['filtering'].items():
                # Avoid infinite recursion for self referencing resource (issue #22)
                if not prefix.find('{0}__'.format(name)) >= 0:
                    # Integer value means this points to a related model
                    if field in [ALL, ALL_WITH_RELATIONS]:
```

**Comment by johnraz** [comment]
```self.schema['filtering']``` is extracted from your very own code, I suspect a trailing coma somewhere after you dict leading to a tuple...

**Comment by paul-wolf** [comment]
You are right. My fault. Apologies. It was a stray comma in the meta class after the filtering attribute that made it into a tuple. 

Thanks for quick response anyway.

**Comment by johnraz** [comment]
No problem, glad I could help ;-)
